# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/rodrigo/workspace/PyStockFlow/src/ui/main.ui'
#
# Created: Wed Oct  6 00:05:31 2010
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(803, 727)
        self.centralwidget = QtGui.QWidget(main)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.operations = QtGui.QWidget()
        self.operations.setObjectName("operations")
        self.gridLayout_2 = QtGui.QGridLayout(self.operations)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtGui.QFrame(self.operations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.stock = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stock.sizePolicy().hasHeightForWidth())
        self.stock.setSizePolicy(sizePolicy)
        self.stock.setMaxLength(10)
        self.stock.setObjectName("stock")
        self.gridLayout.addWidget(self.stock, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.date = QtGui.QDateEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.date.sizePolicy().hasHeightForWidth())
        self.date.setSizePolicy(sizePolicy)
        self.date.setCalendarPopup(True)
        self.date.setObjectName("date")
        self.gridLayout.addWidget(self.date, 1, 0, 1, 1)
        self.operation = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operation.sizePolicy().hasHeightForWidth())
        self.operation.setSizePolicy(sizePolicy)
        self.operation.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.operation.setObjectName("operation")
        self.operation.addItem("")
        self.operation.addItem("")
        self.gridLayout.addWidget(self.operation, 1, 1, 1, 1)
        self.quantity = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantity.sizePolicy().hasHeightForWidth())
        self.quantity.setSizePolicy(sizePolicy)
        self.quantity.setMaxLength(100)
        self.quantity.setObjectName("quantity")
        self.gridLayout.addWidget(self.quantity, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.price = QtGui.QLineEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.price.setInputMask("")
        self.price.setMaxLength(100)
        self.price.setObjectName("price")
        self.gridLayout.addWidget(self.price, 1, 4, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.broker = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.broker.sizePolicy().hasHeightForWidth())
        self.broker.setSizePolicy(sizePolicy)
        self.broker.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.broker.setObjectName("broker")
        self.gridLayout.addWidget(self.broker, 1, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 5, 1, 1)
        self.add = QtGui.QPushButton(self.frame)
        self.add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.add.setIcon(icon)
        self.add.setAutoDefault(True)
        self.add.setDefault(True)
        self.add.setFlat(False)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 1, 6, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.operations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.month = QtGui.QDateEdit(self.operations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.month.sizePolicy().hasHeightForWidth())
        self.month.setSizePolicy(sizePolicy)
        self.month.setMinimumSize(QtCore.QSize(80, 0))
        self.month.setCurrentSection(QtGui.QDateTimeEdit.MonthSection)
        self.month.setCalendarPopup(True)
        self.month.setCurrentSectionIndex(0)
        self.month.setObjectName("month")
        self.gridLayout_2.addWidget(self.month, 1, 3, 1, 1)
        self.trade_list = QtGui.QTableView(self.operations)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trade_list.sizePolicy().hasHeightForWidth())
        self.trade_list.setSizePolicy(sizePolicy)
        self.trade_list.setAlternatingRowColors(True)
        self.trade_list.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.trade_list.setCornerButtonEnabled(False)
        self.trade_list.setObjectName("trade_list")
        self.trade_list.horizontalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.trade_list, 3, 0, 1, 4)
        self.tabWidget.addTab(self.operations, "")
        self.portfolio = QtGui.QWidget()
        self.portfolio.setObjectName("portfolio")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.portfolio)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtGui.QTableView(self.portfolio)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.tabWidget.addTab(self.portfolio, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        main.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 22))
        self.menubar.setObjectName("menubar")
        main.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)
        self.label.setBuddy(self.date)
        self.label_2.setBuddy(self.operation)
        self.label_3.setBuddy(self.stock)
        self.label_4.setBuddy(self.quantity)
        self.label_5.setBuddy(self.price)
        self.label_6.setBuddy(self.broker)

        self.retranslateUi(main)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(main)
        main.setTabOrder(self.tabWidget, self.date)
        main.setTabOrder(self.date, self.operation)
        main.setTabOrder(self.operation, self.stock)
        main.setTabOrder(self.stock, self.quantity)
        main.setTabOrder(self.quantity, self.price)
        main.setTabOrder(self.price, self.broker)
        main.setTabOrder(self.broker, self.add)
        main.setTabOrder(self.add, self.month)
        main.setTabOrder(self.month, self.trade_list)
        main.setTabOrder(self.trade_list, self.tableView)

    def retranslateUi(self, main):
        main.setWindowTitle(QtGui.QApplication.translate("main", "StockFlow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main", "Operação", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("main", "Papel", None, QtGui.QApplication.UnicodeUTF8))
        self.operation.setItemText(0, QtGui.QApplication.translate("main", "Compra", None, QtGui.QApplication.UnicodeUTF8))
        self.operation.setItemText(1, QtGui.QApplication.translate("main", "Venda", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("main", "Quantidade", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main", "Preço", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("main", "Corretora", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("main", "Mês", None, QtGui.QApplication.UnicodeUTF8))
        self.month.setDisplayFormat(QtGui.QApplication.translate("main", "MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.operations), QtGui.QApplication.translate("main", "Operações", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.portfolio), QtGui.QApplication.translate("main", "Portfólio", None, QtGui.QApplication.UnicodeUTF8))

